# create array


In [3]:
import numpy as np

In [40]:
arr = np.array([1,2,3,4])
print(arr)

arr2 = np.arange(12).reshape(3,4)
print(arr2)
print(arr2.shape)
arr2.dtype

[1 2 3 4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


dtype('int64')

In [44]:
i = np.array([[0,1], [1,2]])
j = np.array([[2,1], [3,3]])
print(arr2[i,j])
arr2[i, 2]
arr2[:,j]

[[ 2  5]
 [ 7 11]]


array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [36]:
arr_linspace = np.linspace(0,2,9)
print(arr_linspace)
print(arr_linspace*3)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.   0.75 1.5  2.25 3.   3.75 4.5  5.25 6.  ]
