In [32]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [33]:
hello = tf.constant("Hello ")

In [34]:
world = tf.constant("World")

In [35]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [36]:
print(hello)

Tensor("Const_7:0", shape=(), dtype=string)


In [37]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [38]:
print(result)

b'Hello World'


In [39]:
a = tf.constant(10)

In [40]:
b = tf.constant(20)

In [41]:
type(a)

tensorflow.python.framework.ops.Tensor

In [42]:
a+b

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [43]:
a+b

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [44]:
 a+3

<tf.Tensor 'add_8:0' shape=() dtype=int32>

In [45]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [46]:
print(result)

30


In [47]:
const = tf.constant(10)

In [48]:
fill_mat = tf.fill((4,4), 10)

In [49]:
myzeros = tf.zeros((4,4))

In [50]:
myones = tf.ones((4,4))

In [51]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [52]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [53]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [61]:
sess = tf.InteractiveSession()

In [55]:
for op in my_ops:
#     print(sess.run(op), end='\n'*2)
    print(op.eval(), end='\n'*2)

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.3775806  -1.3764302   1.0204247  -0.60844845]
 [ 1.3880106  -0.2708685  -0.46716842 -0.4196315 ]
 [-0.40038368 -1.5788139   0.18830569 -0.18538934]
 [-0.8314237  -2.7192364   2.4734674   0.70088995]]

[[0.6552882  0.8233558  0.7822343  0.68036723]
 [0.31846547 0.7877859  0.9950683  0.6179513 ]
 [0.41203046 0.0130825  0.78422177 0.63714063]
 [0.42892087 0.27624798 0.08929384 0.5993118 ]]



In [56]:
a = tf.constant([ [1,2], 
                 [3,4] ])

In [57]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [58]:
b = tf.constant([ [10], [100] ])

In [59]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [60]:
result = tf.matmul(a,b)

In [62]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [63]:
result.eval()

array([[210],
       [430]], dtype=int32)